### ISSUE TITLE
Nicer error when output directory doesn't exist

### ISSUE THREAD

**Issue by betatim** [nteract/papermill#201]
When the output directory (called `out` in this case) does not exist you end up with the long output below:
```
$ papermill run-me.ipynb out/run-me.ipynb
Input Notebook:  run-me.ipynb
Output Notebook: out/run-me.ipynb
  0%|                                                                                                 | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/srv/conda/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/srv/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/papermill/cli.py", line 97, in papermill
    report_mode=report_mode,
  File "/srv/conda/lib/python3.6/site-packages/papermill/execute.py", line 65, in execute_notebook
    _execute_parameterized_notebook(nb, kernel_name, progress_bar, log_output, start_timeout)
  File "/srv/conda/lib/python3.6/site-packages/papermill/execute.py", line 131, in _execute_parameterized_notebook
    processor.preprocess(nb, {})
  File "/srv/conda/lib/python3.6/site-packages/papermill/preprocess.py", line 99, in preprocess
    nb, resources = self.papermill_preprocess(nb, resources)
  File "/srv/conda/lib/python3.6/site-packages/papermill/preprocess.py", line 202, in papermill_preprocess
    future.result()
  File "/srv/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/srv/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/srv/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/conda/lib/python3.6/site-packages/papermill/iorw.py", line 170, in write_ipynb
    papermill_io.write(nbformat.writes(nb), path)
  File "/srv/conda/lib/python3.6/site-packages/papermill/iorw.py", line 28, in write
    return self.get_handler(path).write(buf, path)
  File "/srv/conda/lib/python3.6/site-packages/papermill/iorw.py", line 91, in write
    with io.open(path, 'w', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/run-me.ipynb'
Exception ignored in: <bound method tqdm.__del__ of   0%|                              | 0/3 [00:01<?, ?it/s]>
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
  File "/srv/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
  File "/srv/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 441, in _decr_instances
  File "/srv/conda/lib/python3.6/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x7f133bb37ae8; to 'tqdm' at 0x7f133bb1a7f0>
```

I was half expecting an error when I ran it with an output directory that didn't exist. It still took me a moment to confirm that that was indeed what went wrong and not something else.

I am +-0 on creating the directory for the user. I think papermill should check for this though and provide a less puzzling error message.

**Comment by MSeal** [comment]
I think having a nicer error message and checking before trying to run the notebook (when it's using local file system) makes the most sense.

**Comment by harsham4026** [comment]
@MSeal took up this issue and making the changes. Will raise a PR.

**Comment by harsham4026** [comment]
@betatim is it problem for only Local file systems or for other file systems as well?

**Comment by MSeal** [comment]
Thanks @harsham4026
