### ISSUE TITLE
AttributeError: 'PapermillExecutePreprocessor' object has no attribute '_wait_for_reply'

### ISSUE THREAD

**Issue by jordwil** [nteract/papermill#216]
I'm unable to execute notebooks and receive the following error 

`papermill execute_split.ipynb output/test.ipynb`

```Input Notebook:  execute.ipynb
Output Notebook: output/test.ipynb
  0%|                                                                          | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/cli.py", line 97, in papermill
    report_mode=report_mode,
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/execute.py", line 66, in execute_notebook
    _execute_parameterized_notebook(nb, kernel_name, progress_bar, log_output, start_timeout)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/execute.py", line 132, in _execute_parameterized_notebook
    processor.preprocess(nb, {})
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/preprocess.py", line 100, in preprocess
    nb, resources = self.papermill_preprocess(nb, resources)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/preprocess.py", line 190, in papermill_preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 227, in preprocess_cell
    outputs = self.run_cell(cell)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/papermill/preprocess.py", line 276, in run_cell
    exec_reply = self._wait_for_reply(msg_id, cell)
AttributeError: 'PapermillExecutePreprocessor' object has no attribute '_wait_for_reply'```

**Comment by jordwil** [comment]
```# packages in environment at /home/ec2-user/anaconda3:
#
# Name                    Version                   Build  Channel
nbconvert                 5.1.1                    py36_0
[ec2-user@ip-1 Notebooks]$ conda list papermill
# packages in environment at /home/ec2-user/anaconda3:
#
# Name                    Version                   Build  Channel
papermill                 0.15.0                    <pip>```

**Comment by adderRavi** [comment]
Facing the same issue.

**Comment by MSeal** [comment]
@adderRavi papermill 0.15.1 just released with the version pinned to >= 5.3
