### ISSUE TITLE
Exception loading notebook from S3 since botocore-1.12.37

### ISSUE THREAD

**Issue by DemonR** [nteract/papermill#247]
A change in botocore from 1.12.36 to 1.12.37 is causing exception when executing a notebook from S3 path. All versions after 1.12.37 would also produce this exception while 1.12.36 works fine.

```
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    parameters=dict(report_date=report_date, dict_param={1: 2})
  File "/usr/local/lib/python2.7/site-packages/papermill/execute.py", line 51, in execute_notebook
    nb = load_notebook_node(notebook)
  File "/usr/local/lib/python2.7/site-packages/papermill/iorw.py", line 204, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/usr/local/lib/python2.7/site-packages/papermill/iorw.py", line 37, in read
    return self.get_handler(path).read(path)
  File "/usr/local/lib/python2.7/site-packages/papermill/iorw.py", line 126, in read
    s3_client = S3(keyname=cls.keyname)
  File "/usr/local/lib/python2.7/site-packages/papermill/s3.py", line 209, in __init__
    session_vars={'akms_keyname': keyname, 'use_akms': use_akms}
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 123, in __init__
    self.session_var_map.update(session_vars)
  File "/usr/lib64/python2.7/_abcoll.py", line 566, in update
    self[key] = other[key]
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 905, in __setitem__
    self._update_config_store_from_session_vars(key, value)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 926, in _update_config_store_from_session_vars
    config_name, env_vars, default, typecast = config_options
TypeError: 'bool' object is not iterable
```

**Comment by MSeal** [comment]
Thanks for posting -- botocore made some breaking changes which we haven't accounted for here :/. I'll see if I can get some fixes in this weekend.

**Comment by MSeal** [comment]
https://github.com/nteract/papermill/pull/249 fixes the issue. Will get a release out today with the changes
