### ISSUE TITLE
papermill --prepare-only fails if kernel is missing

### ISSUE THREAD

**Issue by pburka** [nteract/papermill#262]
When running with --prepare-only, I don't expect papermill to evaluate my notebook. However, if I attempt to process a notebook whose kernel is not installed in the current environment, I get a "No such kernel" error. Is this expected?

    $ papermill --prepare-only --parameters_yaml "{BEGIN: 20010101, END: 20071231}" -- ./.ipython/notebooks/papermill-test.ipynb  foo.ipynb
    Input Notebook:  ./.ipython/notebooks/papermill-test.ipynb
    Output Notebook: foo.ipynb
    Traceback (most recent call last):
      File "/nas/dft/ire/pburka/.conda/envs/papermill/bin/papermill", line 11, in <module>
        load_entry_point('papermill===0.16.1', 'console_scripts', 'papermill')()
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/cli.py", line 124, in papermill
        report_mode=report_mode,
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/execute.py", line 52, in execute_notebook
        nb = parameterize_notebook(nb, kernel_name, parameters)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/execute.py", line 110, in parameterize_notebook
        param_content = translate_parameters(kernel_name, parameters)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/translators.py", line 212, in translate_parameters
        return papermill_translators.kernel_translator(kernel_name).codify(parameters)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/translators.py", line 21, in kernel_translator
        kernelspec = get_kernel_spec(kernel_name)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 367, in get_kernel_spec
        return KernelSpecManager().get_kernel_spec(kernel_name)
      File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
        raise NoSuchKernel(kernel_name)
    jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3

If I install the missing kernel, papermill completes as expected.

**Comment by VincentBLortie** [comment]
Perhaps:

If --kernel is specified:
1. kernel name (from --kernel)
2. language (from kernelspec)

Else:
1. kernel name (from ipynb)
2. language (from kernelspec)
3. language (from ipynb)

**Comment by MSeal** [comment]
Actually I think you're right about matching 1) kernel name then 2) language.

Would swapping # 2 and # 3 from the else case make more sense? So we check for static values before requiring a kernelspec to be loaded?

If --kernel is specified:

1. kernel name (from --kernel)
2. language (from kernelspec)

Else:

1. kernel name (from ipynb)
2. language (from ipynb)
3. language (from kernelspec)

**Comment by MSeal** [comment]
I think the comment on "this is more complicated than it needs to be" is right. If a user really wants special translators they can deregister/register their own in place of the built-ins. Let's go with this latest pattern you outlined.

**Comment by MSeal** [comment]
PR merged, working on a final issue or two before cutting a release to add the changed behavior.
