### ISSUE TITLE
papermill --prepare-only fails if the notebook has a saved error

### ISSUE THREAD

**Issue by pburka** [nteract/papermill#263]
If papermill is invoked with --prepare-only on a notebook with a saved KeyboradInterrupt error (or possibly other errors), it fails as if the error occurred while running papermill.

**Expected behavior:** papermill should not report an error and should exit 0 (success).

**Steps to reproduce:**

1. Create a new, empty jupyter notebook with a single cell like this:
```
import time
time.sleep(1000)
```
2. Evaluate the cell, then interrupt the kernel while it's running (e.g. press the 'stop' button in jupyter).
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-10-31b17fe32cbc> in <module>()
      1 import time
----> 2 time.sleep(1000)

KeyboardInterrupt: 
```

3. Save the notebook.

4. Run papermill on the saved notebook:
```
$ papermill --prepare-only --parameters_yaml "{foo: bar}" -- ./.ipython/notebooks/papermill-test.ipynb  foo.ipynb
Input Notebook:  ./.ipython/notebooks/papermill-test.ipynb
Output Notebook: foo.ipynb
Traceback (most recent call last):
  File "/nas/dft/ire/pburka/.conda/envs/papermill/bin/papermill", line 11, in <module>
    load_entry_point('papermill===0.16.1', 'console_scripts', 'papermill')()
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/cli.py", line 124, in papermill
    report_mode=report_mode,
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/execute.py", line 70, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/nas/dft/ire/pburka/.conda/envs/papermill/lib/python3.6/site-packages/papermill/execute.py", line 182, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-10-31b17fe32cbc> in <module>()
      1 import time
----> 2 time.sleep(1000)

KeyboardInterrupt: 

$ echo $?
1
```

**Comment by betatim** [comment]
I am not sure if this is on purpose or not. If it is we should document it somewhere. Maybe there is a use case for this style of behaviour?

To fix it we have to indent the following two lines:
https://github.com/nteract/papermill/blob/29ccb408d5865f950f019b5aa3f5a2640ca23aeb/papermill/execute.py#L69-L70

so they only run if the notebook is executed.

Do you want to create a Pull Request to do this and add a test to stop the behaviour from coming back?

**Comment by pburka** [comment]
I'll try to get to this within a few days.

**Comment by pburka** [comment]
I'm going to try to get to it tomorrow.
