### ISSUE TITLE
--report-mode key error

### ISSUE THREAD

**Issue by wrathagom** [nteract/papermill#282]
I am trying to run paper mill with the `--report-mode` option, but I am getting the below error. This is using Papermill 0.16.2.

```
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/papermill/cli.py", line 155, in papermill
    report_mode=report_mode,
  File "/opt/conda/lib/python3.6/site-packages/papermill/execute.py", line 52, in execute_notebook
    nb = parameterize_notebook(nb, kernel_name, parameters, report_mode)
  File "/opt/conda/lib/python3.6/site-packages/papermill/execute.py", line 116, in parameterize_notebook
    newcell.metadata['jupyter']['source_hidden'] = True
KeyError: 'jupyter'
```

Here is the command I am trying to execute:

```
papermill --report-mode s3://my-bucket/home/SQL\ Viz.ipynb s3://my-bucket/home/SQL\ Viz\ Test.ipynb -p username username -p password password
```

I'm happy to provide anything else that could prove valuable in helping me discover the problem.

**Comment by wrathagom** [comment]
I only get this error when specifying parameters. If I remove all of the parameters then it works fine.

**Comment by MSeal** [comment]
Taking a look now

**Comment by MSeal** [comment]
Looks like it was already fixed in the changes staged for 0.17. The new release should be going out this next week, or you can grab the master commit now to unblock yourself.

**Comment by wrathagom** [comment]
Great, thanks.
