### ISSUE TITLE
tqdm.auto doesn't exist in all versions of tqdm

### ISSUE THREAD

**Issue by ctb** [nteract/papermill#287]
I had to upgrade from tqdm 4.19.4 to tqdm 4.29.1 to use papermill -- maybe add a minimum version string in requirements?

```
% papermill try_params.ipynb out.ipynb -p a 2 -p b 6
Traceback (most recent call last):
  File "/Users/t/dev/py36/bin/papermill", line 7, in <module>
    from papermill.cli import papermill
  File "/Users/t/dev/py36/lib/python3.6/site-packages/papermill/__init__.py", line 10, in <module>
    from .execute import execute_notebook
  File "/Users/t/dev/py36/lib/python3.6/site-packages/papermill/execute.py", line 13, in <module>
    from .engines import papermill_engines
  File "/Users/t/dev/py36/lib/python3.6/site-packages/papermill/engines.py", line 16, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
% pip install tqdm
Requirement already satisfied: tqdm in /Users/t/dev/py36/lib/python3.6/site-packages (4.19.4)
% pip install -U tqdm
Collecting tqdm
  Downloading https://files.pythonhosted.org/packages/ed/d6/3458d39cf4978f4ece846295e83daf5ece710ab0a4106774f7f7b3a68697/tqdm-4.29.1-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 1.0MB/s 
Installing collected packages: tqdm
  Found existing installation: tqdm 4.19.4
    Uninstalling tqdm-4.19.4:
      Successfully uninstalled tqdm-4.19.4
Successfully installed tqdm-4.29.1
```

**Comment by MSeal** [comment]
I'll quickly pop out 0.17.1 so this doesn't hit too many people

**Comment by resperic** [comment]
I tried to install tqdm with conda, but would have had to downgrade my version of python from py36_1 to py36_0.   And what else might that mess up...

**Comment by MSeal** [comment]
@resperic Don't think so, that sounds like a purely conda or tqdm issue.

**Comment by casperdcl** [comment]
`tqdm` doesn't set any requirement on python version so must be a conda issue. See https://github.com/tqdm/tqdm/issues/701

**Comment by mixvc** [comment]
> pip install -U tqdm

Thanks. I was having trouble with Import error: auto can not found in tqdm. But the command solves the issue.
