### ISSUE TITLE
Using Python 3.5 causes error in papermill 0.18.1

### ISSUE THREAD

**Issue by gogasca** [nteract/papermill#317]
May be related to https://github.com/jupyterlab/jupyterlab-toc/issues/26

```
papermill gs://cloud-samples-data/papermill/samples/test.ipynb out.ipynb

Input Notebook:  gs://cloud-samples-data/papermill/samples/test.ipynb
Output Notebook: out.ipynb
Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/papermill/cli.py", line 165, in papermill
    cwd=cwd,
  File "/usr/local/lib/python3.5/dist-packages/papermill/execute.py", line 68, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/usr/local/lib/python3.5/dist-packages/papermill/iorw.py", line 309, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/usr/local/lib/python3.5/dist-packages/nbformat/__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by gogasca** [comment]
Do you think a change in iorw.py may fix the issue:
nb = nbformat.reads(papermill_io.read(notebook_path).decode('utf-8'), as_version=4)

I'm trying to reproduce, as a colleague reported this problem

**Comment by MSeal** [comment]
It's the right problem -- didn't think about python3.5 constraints here, slightly wrong fix. We need to catch in `PapermillIO.read` when the response type is `bytes` to perform the decode('utf-8'). This would be the safest approach as you can't always decode the string.

**Comment by MSeal** [comment]
Can you get a simple version of `gs://cloud-samples-data/papermill/samples/test.ipynb out.ipynb` so we can add it to a unittest for this case and confirm python 2 behavior with such a fix?

**Comment by gogasca** [comment]
Created https://github.com/nteract/papermill/pull/319

**Comment by MSeal** [comment]
0.18.2 has the fix
