### ISSUE TITLE
Passing dates through YAML

### ISSUE THREAD

**Issue by stevenmanton** [nteract/papermill#345]
I'm running into a bug when passing dates as a parameter into a notebook through the YAML configuration. 

As a simple example, suppose I have the following parameter in a notebook:
![image](https://user-images.githubusercontent.com/3666725/56532013-e1dd5280-6509-11e9-97e6-9819781978bc.png)

This method of executing the notebook works fine:
```
$ papermill papermill-date.ipynb blah.ipynb -p a_date "2019-01-01"
Input Notebook:  /tmp/papermill-date.ipynb
Output Notebook: blah.ipynb
100%|██████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.24s/it]
```

However, passing the parameterization through YAML leads to the following exception:
```
$ papermill papermill-date.ipynb blah.ipynb -y "a_date: 2019-01-01"
/Users/santon/tools/python/lib/python3.7/site-packages/papermill/cli.py:148: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parameters_final.update(yaml.load(params))
Input Notebook:  papermill-date.ipynb
Output Notebook: blah.ipynb
Input notebook does not contain a cell with tag 'parameters'
  0%|                                                      | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/santon/tools/python/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/Users/santon/tools/python/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/cli.py", line 165, in papermill
    cwd=cwd,
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/execute.py", line 96, in execute_notebook
    start_timeout=start_timeout,
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 56, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 294, in execute_notebook
    nb_man.notebook_start()
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 76, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 174, in notebook_start
    self.save()
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 76, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/engines.py", line 138, in save
    write_ipynb(self.nb, self.output_path)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/papermill/iorw.py", line 337, in write_ipynb
    papermill_io.write(nbformat.writes(nb), path)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/nbformat/__init__.py", line 111, in writes
    return versions[version].writes_json(nb, **kwargs)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/nbformat/v4/nbjson.py", line 58, in writes
    return py3compat.cast_unicode_py2(json.dumps(nb, **kwargs), 'utf-8')
  File "/Users/santon/tools/python/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/santon/tools/python/lib/python3.7/site-packages/nbformat/v4/nbjson.py", line 22, in default
    return json.JSONEncoder.default(self, obj)
  File "/Users/santon/tools/python/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

Quoting the YAML seems to work as well:
```
$ papermill papermill-date.ipynb blah.ipynb -y "a_date: '2019-01-01'"
/Users/santon/tools/python/lib/python3.7/site-packages/papermill/cli.py:148: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parameters_final.update(yaml.load(params))
Input Notebook:  papermill-date.ipynb
Output Notebook: blah.ipynb
100%|██████████████████████████████████████████████| 2/2 [00:03<00:00,  1.72s/it]
```

Any thoughts on this?

**Comment by MSeal** [comment]
Ahhh so the yaml parser is converting `"a_date: 2019-01-1"` to `{'a_date': datetime.date(2019, 1, 1)}` and the code after that doesn't accommodate date object translation to each language's supported conversion. Basically `"a_date: '2019-01-01'"` converts to `{'a_date': '2019-01-01'} which preserves the argument as a string.

Papermill should either figure out how to preserve the datetime object (difficult across languages / versions) or coerce that date back into it's original string input.
