### ISSUE TITLE
Piping papermill into nbconvert triggers an encoding error on Python 2

### ISSUE THREAD

**Issue by mwouts** [nteract/papermill#420]
For some notebooks (possibly those with non-ascii characters in the output cells, I will have to confirm), piping papermill into nbconvert triggers an encoding error (stacktrace below).

Maybe we could replace

https://github.com/nteract/papermill/blob/01ec212f14c76860f3788f6f92f9be27d5742ea3/papermill/iorw.py#L104

with

```python
return sys.stdout.write(buf.encode('utf-8'))
```

The substitution above fixes my issue locally, but possibly we need to do this conditionally on the type of `buf`.  And maybe a similar fix on the standard input would be appropriate (see also #317). 

I have not been able to extract a MRE yet, but the stacktrace is
```
Traceback (most recent call last):
  File "/home/mwouts/conda/envs/jp2/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/papermill/cli.py", line 254, in papermill
    cwd=cwd,
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/papermill/execute.py", line 107, in execute_notebook
    write_ipynb(nb, output_path)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/papermill/iorw.py", line 363, in write_ipynb
    papermill_io.write(nbformat.writes(nb), path)
  File "/home/mwouts/conda/envs/jp2/lib/python2.7/site-packages/papermill/iorw.py", line 104, in write
    return sys.stdout.write(buf)
```

**Comment by MSeal** [comment]
Ahh we should be doing `sys.stdout.write(buf.encode('utf-8'))` on python 2 and `sys.stdout.buffer.write(buf.encode('utf-8'))` on python 3. Thanks for raising the issue. If you wanted to submit a PR I'll gladly get it merged and into the next patch release.

**Comment by mwouts** [comment]
Sure, I can do that. I will also try to contribute a simple example and add it into the tests.
Also, do you expect that we should do something similar on the `stdin` part?

**Comment by MSeal** [comment]
I don't think you need to handle stdin. I tested out passing unicode characters into papermill via the pipe in both python 2 and 3 and it seems fine. The upstream libraries handle translation to utf-8 for us and the buffer doesn't crash reading in encoded text.

**Comment by MSeal** [comment]
@mwouts Do you think you could get that PR up this week? I want to get a release out with some fixes for a few issues.

**Comment by mwouts** [comment]
Sure, I will do that. By the way I now have a short example that reproduces the issue (see below), but maybe you will prefer even tests in the spirit `test_read_utf8` or `test_write_utf8` from `test_iorw.py`?

```
echo 'import world_bank_data as wb; wb.get_countries()' | jupytext --from py --to ipynb --set-kernel - | papermill > out.ipynb
```
