### ISSUE TITLE
Execution stops on exceptions

### ISSUE THREAD

**Issue by marketneutral** [nteract/papermill#464]
I am confused by the behavior of papermill when an underlying notebook has an exception. [Part 2: Scheduling Notebooks at Netflix](https://medium.com/netflix-techblog/scheduling-notebooks-348e6c14cfd6), notes that a key value proposition of the papermill notebook workflow is that *the notebook output file is the log*. In the section **"Self Service Debugging"** the article talks about inspecting the notebook output to see the errors thrown (in that case a `ConnectionError`): 

> Let’s dig into how we would deal with a failure. Say something went wrong in our example notebook from earlier. How might we debug and fix the issue? The first place we’d want to look is the notebook output. It will have a stack trace, and ultimately any output information related to an error.

However, it seems that the default behavior of papermill does not support this. As an example,

- I make a notebook with a single cell: `1/0`
- I run this with `papermill notebook.ipynb output.ipynb`

I expect that I will get a notebook, `output.ipynb` with

![image](https://user-images.githubusercontent.com/16124573/71901429-ec8a5700-312d-11ea-96ff-63ce4fef8ac0.png)

however, instead, papermill stops execution at the CLI and throws

```
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 11, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/papermill/cli.py", line 165, in papermill
    cwd=cwd,
  File "/opt/conda/lib/python3.6/site-packages/papermill/execute.py", line 101, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.6/site-packages/papermill/execute.py", line 185, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-4-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero
```

**There is no `output.ipynb` to inspect.** How does one get papermill to operate as described in the Medium post?

**Comment by marketneutral** [comment]
Ah, my mistake. I was going to delete the issue, but will leave it in case it's helpful for others. In fact `output.ipynb` is created and the top cell is a markdown cell with `An Exception was encountered at 'In [1]'.`
