### ISSUE TITLE
ValueError: Invalid file object: <zmq.asyncio.Socket object at 0x7f4bb838dfa8>

### ISSUE THREAD

**Issue by jonatasfreitasv** [nteract/papermill#516]
Try with a simple single cell notebook for "Hello wolrd"...

**The fail message is:**
`ValueError: Invalid file object: <zmq.asyncio.Socket object at 0x7f4bb838dfa8>`

**Use this code:**
```
pm.execute_notebook(
    './tst.ipynb',
    './4-simulation-out.ipynb',
    parameters = dict(simulation=True, simulation_forecast_week=4),
    kernel_name='python3'    
)
```

I`m use a Anaconda Enterprise (with conda enviroment) with a Jupyter Lab.

Stack trace (when a try to run in terminal with env activated):
```
Generating grammar tables from /opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /opt/continuum/.cache/black/19.10b0/Grammar3.6.10.final.0.pickleWriting failed: [Errno 2] No such file or directory: '/opt/continuum/.cache/black/19.10b0/tmpgoh__b0i'Generating grammar tables from /opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /opt/continuum/.cache/black/19.10b0/PatternGrammar3.6.10.final.0.pickleWriting failed: [Errno 2] No such file or directory: '/opt/continuum/.cache/black/19.10b0/tmp2pjndfgf'
Input notebook does not contain a cell with tag 'parameters'Executing:   0%|                                                                                                                          | 0/77 [00:00<?, ?cell/s]Traceback (most recent call last):  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/asyncio/base_events.py", line 429, in run_forever
    raise RuntimeError('This event loop is already running')RuntimeError: This event loop is already running
ERROR:tornado.general:Uncaught exception in ZMQStream callbackTraceback (most recent call last):
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback    callback(*args, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher    return self.dispatch_shell(stream, msg)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell    self.pre_handler_hook()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread




Executing:   0%|                                                                                                                          | 0/77 [01:05<?, ?cell/s]
Traceback (most recent call last):
  File "/opt/continuum/anaconda/envs/anaconda50_py36/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/cli.py", line 238, in papermill
    execution_timeout=execution_timeout,
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/execute.py", line 106, in execute_notebook
    **engine_kwargs
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/papermill/clientwrap.py", line 36, in execute
    with self.setup_kernel(**kwargs):
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/nbclient/client.py", line 425, in setup_kernel
    self.start_new_kernel_client(**kwargs)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/nbclient/util.py", line 72, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/nbclient/util.py", line 51, in just_run
    return loop.run_until_complete(coro)
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/nbclient/client.py", line 399, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/nbclient/util.py", line 83, in ensure_async
    result = await obj
  File "/opt/continuum/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/jupyter_client/asynchronous/client.py", line 143, in wait_for_ready
    raise RuntimeError("Kernel didn't respond in %d seconds" % timeout)
RuntimeError: Kernel didn't respond in 60 seconds
```

**Comment by MSeal** [comment]
Unless there's an additional issue, this looks like you have an older nbclient installed. The recent 0.4.0 release catches this issue for you and fixes it, but basically your running papermill from inside an existing event loop.

If that doesn't fix it, post your package install versions and detail from where / how you're calling papermill since the stack is saying it's from inside an existing async loop.
