### ISSUE TITLE
is it possible to disable black?

### ISSUE THREAD

**Issue by zyxue** [nteract/papermill#534]
I'm running `papermill.execute_notebook` inside a docker container, and I'm seeing 
```
INFO:blib2to3.pgen2.driver:Generating grammar tables from /usr/local/lib/python3.8/site-packages/blib2to3/Grammar.txt
INFO:blib2to3.pgen2.driver:Writing grammar tables to /root/.cache/black/19.10b0/Grammar3.8.3.final.0.pickle
INFO:blib2to3.pgen2.driver:Writing failed: [Errno 2] No such file or directory: '/root/.cache/black/19.10b0/tmp658iz_6x'
INFO:blib2to3.pgen2.driver:Generating grammar tables from /usr/local/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
INFO:blib2to3.pgen2.driver:Writing grammar tables to /root/.cache/black/19.10b0/PatternGrammar3.8.3.final.0.pickle
INFO:blib2to3.pgen2.driver:Writing failed: [Errno 2] No such file or directory: '/root/.cache/black/19.10b0/tmpfyzx0mb5'
```

My understanding is that papermill tries to call black to format the "parameters" it's injecting into the notebook, but since black has never been run before, and no cache directory has been set inside the container, hence these messages are output, is that right, and if so, is it possible to disable black somehow?

I'm using `papermill = "^2.1.1"`

Although they're harmless in a way, but I'd prefer to remove the noise from the log.

**Comment by MSeal** [comment]
There's currently not a flag to disable black for Python kernel inputs. There would either need to be a flag added or we should try to make black run without warning messages for cache directories. I haven't looked into how one might do the latter.

**Comment by dcnadler** [comment]
I would like to disable black because it is causing an error

I'm using
```
black==20.8b1
papermill==2.2.2
```

Specifically, black throws an `InvalidInput` error with mixed quote bytes objects. For example:
```python
input_notebook = 'test_input.ipynb'
output_path = 'output/test_output.ipynb'
parameters = dict(x=b"test'")

pm.execute_notebook(
   input_notebook,
   output_path,
   parameters=parameters,
);
```

```
---------------------------------------------------------------------------
InvalidInput                              Traceback (most recent call last)
<ipython-input-92-374ac18258d0> in <module>
      6    input_notebook,
      7    output_path,
----> 8    parameters=parameters,
      9 );

/usr/local/lib/python3.6/dist-packages/papermill/execute.py in execute_notebook(input_path, output_path, parameters, engine_name, request_save_on_cell_execute, prepare_only, kernel_name, progress_bar, log_output, stdout_file, stderr_file, start_timeout, report_mode, cwd, **engine_kwargs)
     89         # Parameterize the Notebook.
     90         if parameters:
---> 91             nb = parameterize_notebook(nb, parameters, report_mode)
     92 
     93         nb = prepare_notebook_metadata(nb, input_path, output_path, report_mode)

/usr/local/lib/python3.6/dist-packages/papermill/parameterize.py in parameterize_notebook(nb, parameters, report_mode, comment)
     78 
     79     # Generate parameter content based on the kernel_name
---> 80     param_content = translate_parameters(kernel_name, language, parameters, comment)
     81 
     82     newcell = nbformat.v4.new_code_cell(source=param_content)

/usr/local/lib/python3.6/dist-packages/papermill/translators.py in translate_parameters(kernel_name, language, parameters, comment)
    552 
    553 def translate_parameters(kernel_name, language, parameters, comment='Parameters'):
--> 554     return papermill_translators.find_translator(kernel_name, language).codify(parameters, comment)

/usr/local/lib/python3.6/dist-packages/papermill/translators.py in codify(cls, parameters, comment)
    190 
    191             fm = black.FileMode(string_normalization=False)
--> 192             content = black.format_str(content, mode=fm)
    193         return content
    194 

/usr/local/lib/python3.6/dist-packages/black/__init__.py in format_str(src_contents, mode)
    972 
    973     """
--> 974     src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
    975     dst_contents = []
    976     future_imports = get_future_imports(src_node)

/usr/local/lib/python3.6/dist-packages/black/__init__.py in lib2to3_parse(src_txt, target_versions)
   1081             exc = InvalidInput(f"Cannot parse: {lineno}:{column}: {faulty_line}")
   1082     else:
-> 1083         raise exc from None
   1084 
   1085     if isinstance(result, Leaf):

InvalidInput: Cannot parse: 2:7: x = "b"test'""
```

I haven't done too much testing, but variations such as `b'"test"'` also throw an error, while non-mixed quotes bytes don't cause issues, e.g. `b'test'`

Not sure if this is a bug in black, but would be great to disable in papermill

**Comment by willingc** [comment]
Black using typing `str` for the `format_str` function and the byte string is failing with a type error in Black.

```
>>> import black
>>> black.format_str(b"test'", mode=black.FileMode(string_normalization=False))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willingc/.pyenv/versions/3.9.2/lib/python3.9/site-packages/black/__init__.py", line 974, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/willingc/.pyenv/versions/3.9.2/lib/python3.9/site-packages/black/__init__.py", line 1066, in lib2to3_parse
    src_txt += "\n"
TypeError: can't concat str to bytes

# Another example as a str
>>> black.format_str("test'", mode=black.FileMode(string_normalization=False))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willingc/.pyenv/versions/3.9.2/lib/python3.9/site-packages/black/__init__.py", line 974, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/willingc/.pyenv/versions/3.9.2/lib/python3.9/site-packages/black/__init__.py", line 1083, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 1:4: test'
```

**Comment by stonebig** [comment]
also Black is incompatible with PyPy3 at the moment, because using typed_ast.... very sad

**Comment by tanguycdls** [comment]
+1 to make it an optional requirement, Black has the habit of locking a lot of its deps in the setup.py (https://github.com/psf/black/blob/41e670064063e3e221b1c3c40db5aaae784b5231/setup.py#L74) that creates a lot of issues later while using Pipenv or Petry environments. 

What would you think of adding black to extra_requires and add a try except import error here : https://github.com/nteract/papermill/blob/d77db79b8620bb3d922f8a4cf0718aa9725bd423/papermill/translators.py#L189 

people that still want it formatted can install the extra and the rest of users can use it without.
