### ISSUE TITLE
Papermill fails for notebooks without nb.metadata.kernelspec.language (e.g. from VSCode)

### ISSUE THREAD

**Issue by kennysong** [nteract/papermill#581]
I think notebooks created through VSCode do not specify the language in the kernelspec.

So when I try to run Papermill, it fails with the stack trace:

```
Traceback (most recent call last):
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/ipython_genutils/ipstruct.py", line 132, in __getattr__
    result = self[key]
KeyError: 'language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kennysong/GDrive/Projects/test/env/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
    execution_timeout=execution_timeout,
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/papermill/execute.py", line 91, in execute_notebook
    nb = parameterize_notebook(nb, parameters, report_mode)
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/papermill/parameterize.py", line 77, in parameterize_notebook
    language = nb.metadata.kernelspec.language
  File "/Users/kennysong/GDrive/Projects/test/env/lib/python3.7/site-packages/ipython_genutils/ipstruct.py", line 134, in __getattr__
    raise AttributeError(key)
AttributeError: language
```

You can replicate this by creating a blank `.ipynb` from VSCode, and then trying to run it with Papermill (with at least one parameter).

I think an easy workaround would be to allow the user to specify "language" as a command line flag.

**Comment by MSeal** [comment]
We should have a language flag to overwrite, however I from digging I think there's an actual bug here. The path we're reading from is the v3 spec path which is _usually_ also filled in by interfaces for backwards compatibility. Instead we should be always reading from the v4 language_info location with a fallback to the v3 is not found.
