### ISSUE TITLE
Papermill execute_notebook() seems to break for nbclient < 0.7.0

### ISSUE THREAD

**Issue by rmshkv** [nteract/papermill#716]
## 🐛 Bug

Relevant package versions:

```bash
papermill=2.3.4
nbclient=0.6.0
python=3.9.0
```

When trying to batch execute notebooks with `pm.execute_notebook()`, in environments with `nbclient < 0.7.0` I get the following error:

```bash
Traceback (most recent call last):
  File "/glade/u/home/eromashkova/codes/cesm-diagnostics-infrastructure/src/run.py", line 195, in <module>
    o = pm.execute_notebook(
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/papermill/execute.py", line 107, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/papermill/engines.py", line 359, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/papermill/engines.py", line 418, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/papermill/clientwrap.py", line 43, in execute
    with self.setup_kernel(**kwargs):
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/nbclient/client.py", line 561, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/glade/work/eromashkova/miniconda3/envs/test-env-broken/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'NotebookClient.async_start_new_kernel' was never awaited
```

Currently according to `papermill`’s dependencies `nbclient >= 0.2.0` should work.

In my case, this is causing issues because I’m trying to set up an environment with both `papermill` and `jupyter-book`, and `jupyter-book` requires `jupyter-cache`, which needs `nbclient>=0.2,<0.6`, so these packages aren’t compatible with each other. I imagine this workflow isn’t an uncommon usecase, so it would be very helpful to figure out how to resolve this issue.

**Comment by rmshkv** [comment]
Resolved by dependency changes in https://github.com/executablebooks/jupyter-cache/releases/tag/v0.6.0 !

**Comment by guigoruiz1** [comment]
Hello, I am having this same problem with 

```
papermill==2.5
nbclient==0.9.0
Jupyter-core>5.3.1
python==3.11.6
```

I can only run with `Jupyter-core<=5.3.1`.
