### ISSUE TITLE
Latest release not installable from sdist

### ISSUE THREAD

**Issue by blink1073** [nteract/papermill#737]
## 🐛 Bug

I believe `docs/requirements.txt` needs to be added to the sdist.

https://github.com/jupyter/jupyter_client/actions/runs/6745219270/job/18336937722?pr=995

```bash
pip download --no-deps --no-binary papermill papermill
  Collecting papermill
    Downloading papermill-2.5.0.tar.gz (79 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 1.6 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [22 lines of output]
        Traceback (most recent call last):
          File "/home/runner/test_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/home/runner/test_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/runner/test_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-kwn8q[137](https://github.com/jupyter/jupyter_client/actions/runs/6745219270/job/18336937722?pr=995#step:4:141)/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-kwn8q137/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-kwn8q137/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
            super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
          File "/tmp/pip-build-env-kwn8q137/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
            exec(code, locals())
          File "<string>", line 47, in <module>
          File "<string>", line 39, in read_reqs
          File "<string>", line 32, in read
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-download-73zowctq/papermill_88120fa6b970478f82555287473fdcba/docs/requirements.txt'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Error: Process completed with exit code 1.
```

**Comment by MSeal** [comment]
Ahh thanks for raising. The manifest didn't get respected for some reason. I'll work on getting that fixed.
