### ISSUE TITLE
Master build failing

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#89]
Looks like a dependency broke somewhere. Discovered it in https://github.com/nteract/papermill/pull/88 where I though I had messed up but clean master recreates the issue now for me. I have an older virtualenv where the tests pass while a fresh env fails. The error is with traitlets but that version didn't change so it's another package interacting with it. If it doesn't resolve itself beforehand I'll look more deeply at it on Monday.

Broken pip list
```
$ pip freeze -l
ansiwrap==0.8.3
attrs==17.4.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.2
boto3==1.5.14
botocore==1.8.28
certifi==2017.11.5
chardet==3.0.4
click==6.7
codecov==2.0.13
configparser==3.5.0
coverage==4.4.2
decorator==4.2.0
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.2.0
html5lib==1.0.1
idna==2.6
ipykernel==4.7.0
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.1
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
mock==2.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2
numpy==1.14.0
pandas==0.22.0
pandocfilters==1.4.2
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.3.1
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
Pygments==2.2.0
pytest==3.3.2
pytest-cov==2.5.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
s3transfer==0.1.12
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
terminado==0.8.1
testpath==0.3.1
textwrap3==0.9.1
tornado==4.5.3
tqdm==4.19.5
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.0
```

Working pip list
```
$ pip freeze -l
ansiwrap==0.8.3
astroid==1.5.3
attrs==17.3.0
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.1
boto3==1.4.7
botocore==1.7.44
certifi==2017.11.5
chardet==3.0.4
click==6.7
codecov==2.0.10
configparser==3.5.0
coverage==4.4.2
decorator==4.1.2
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
html5lib==1.0b10
idna==2.6
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.0.4
isort==4.2.15
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.8.1
mock==2.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.1
numpy==1.13.3
pandas==0.21.0
pandocfilters==1.4.2
papermill==0.11.5
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.3.0
pickleshare==0.7.4
pkginfo==1.4.1
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
Pygments==2.2.0
pylint==1.7.4
pytest==3.3.1
pytest-cov==2.5.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
requests-toolbelt==0.8.0
s3transfer==0.1.11
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
terminado==0.7
testpath==0.3.1
textwrap3==0.9.1
tornado==4.5.2
tqdm==4.19.4
traitlets==4.3.2
twine==1.9.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.7
wrapt==1.10.11
```

**Comment by willingc** [comment]
@MSeal What's the traitlets error?

**Comment by MSeal** [comment]
```
======================================================================
ERROR: papermill.tests.test_conf (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: papermill.tests.test_conf
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/mseal/Workspace/papermill/papermill/__init__.py", line 7, in <module>
    from .api import display, record, read_notebook, read_notebooks
  File "/home/mseal/Workspace/papermill/papermill/api.py", line 11, in <module>
    import IPython
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 120, in <module>
    class Application(SingletonConfigurable):
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() takes exactly 2 arguments (1 given)


======================================================================
ERROR: papermill.tests.test_cli (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: papermill.tests.test_cli
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/mseal/Workspace/papermill/papermill/__init__.py", line 7, in <module>
    from .api import display, record, read_notebook, read_notebooks
  File "/home/mseal/Workspace/papermill/papermill/api.py", line 11, in <module>
    import IPython
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 120, in <module>
    class Application(SingletonConfigurable):
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() takes exactly 2 arguments (1 given)


======================================================================
ERROR: papermill.tests.test_s3 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: papermill.tests.test_s3
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/mseal/Workspace/papermill/papermill/__init__.py", line 7, in <module>
    from .api import display, record, read_notebook, read_notebooks
  File "/home/mseal/Workspace/papermill/papermill/api.py", line 11, in <module>
    import IPython
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 120, in <module>
    class Application(SingletonConfigurable):
  File "/home/mseal/Workspace/papermill/.test/local/lib/python2.7/site-packages/traitlets/config/application.py", line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() takes exactly 2 arguments (1 given)
```

**Comment by MSeal** [comment]
Looks like a fresh virtualenv runs now, so whomever published a bad depedency version fixed it this morning.

**Comment by willingc** [comment]
Confirming that it works in a virtualenv for Python2:
```
$ pytest -v papermill/tests
================================================= test session starts ==================================================
platform darwin -- Python 2.7.13, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /Users/carol/code/projects-nteract/papermill/my2env/bin/python2.7
cachedir: .cache
rootdir: /Users/carol/code/projects-nteract/papermill, inifile:
plugins: cov-2.5.1
collected 43 items

papermill/tests/test_api.py::TestNotebookClass::test PASSED                                                      [  2%]
papermill/tests/test_api.py::TestNotebookClass::test_bad_file_ext PASSED                                         [  4%]
papermill/tests/test_api.py::TestNotebookClass::test_path_without_node PASSED                                    [  6%]
papermill/tests/test_api.py::TestNotebookCollection::test PASSED                                                 [  9%]
papermill/tests/test_api.py::test_display PASSED                                                                 [ 11%]
papermill/tests/test_api.py::test_record PASSED                                                                  [ 13%]
papermill/tests/test_cli.py::test_resolve_type[True-True] PASSED                                                 [ 16%]
papermill/tests/test_cli.py::test_resolve_type[False-False] PASSED                                               [ 18%]
papermill/tests/test_cli.py::test_resolve_type[None-None] PASSED                                                 [ 20%]
papermill/tests/test_cli.py::test_resolve_type[12.51-12.51] PASSED                                               [ 23%]
papermill/tests/test_cli.py::test_resolve_type[10-10] PASSED                                                     [ 25%]
papermill/tests/test_cli.py::test_resolve_type[hello world-hello world] PASSED                                   [ 27%]
papermill/tests/test_cli.py::test_resolve_type[\U0001f60d-\U0001f60d] PASSED                                     [ 30%]
papermill/tests/test_cli.py::test_is_float[13.71-True] PASSED                                                    [ 32%]
papermill/tests/test_cli.py::test_is_float[False-False] PASSED                                                   [ 34%]
papermill/tests/test_cli.py::test_is_float[None-False] PASSED                                                    [ 37%]
papermill/tests/test_cli.py::test_is_float[-8.2-True] PASSED                                                     [ 39%]
papermill/tests/test_cli.py::test_is_float[10-True0] PASSED                                                      [ 41%]
papermill/tests/test_cli.py::test_is_float[10-True1] PASSED                                                      [ 44%]
papermill/tests/test_cli.py::test_is_float[12.31-True] PASSED                                                    [ 46%]
papermill/tests/test_cli.py::test_is_float[hello world-False] PASSED                                             [ 48%]
papermill/tests/test_cli.py::test_is_float[\U0001f60d-False] PASSED                                              [ 51%]
papermill/tests/test_cli.py::test_is_int[13.71-True] PASSED                                                      [ 53%]
papermill/tests/test_cli.py::test_is_int[False-False] PASSED                                                     [ 55%]
papermill/tests/test_cli.py::test_is_int[None-False] PASSED                                                      [ 58%]
papermill/tests/test_cli.py::test_is_int[-8.2-True] PASSED                                                       [ 60%]
papermill/tests/test_cli.py::test_is_int[-23.2-False] PASSED                                                     [ 62%]
papermill/tests/test_cli.py::test_is_int[10-True] PASSED                                                         [ 65%]
papermill/tests/test_cli.py::test_is_int[13-True] PASSED                                                         [ 67%]
papermill/tests/test_cli.py::test_is_int[hello world-False] PASSED                                               [ 69%]
papermill/tests/test_cli.py::test_is_int[\U0001f60d-False] PASSED                                                [ 72%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_backslash_params PASSED                               [ 74%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_backslash_quote_params PASSED                         [ 76%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_cell_insertion PASSED                                 [ 79%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_double_backslash_quote_params PASSED                  [ 81%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_no_tags PASSED                                        [ 83%]
papermill/tests/test_execute.py::TestNotebookHelpers::test_quoted_params PASSED                                  [ 86%]
papermill/tests/test_execute.py::TestBrokenNotebook1::test PASSED                                                [ 88%]
papermill/tests/test_execute.py::TestBrokenNotebook2::test PASSED                                                [ 90%]
papermill/tests/test_execute.py::TestLogging::test_logging PASSED                                                [ 93%]
papermill/tests/test_iorw.py::TestHttpHandler::test_listdir PASSED                                               [ 95%]
papermill/tests/test_iorw.py::TestHttpHandler::test_read PASSED                                                  [ 97%]
papermill/tests/test_iorw.py::TestHttpHandler::test_write PASSED                                                 [100%]

============================================== 43 passed in 13.42 seconds ==============================================
(my2env)
carol at cw-pro in ~/code/projects-nteract/papermill on master [?$]
```
*pip*
```
$ pip freeze -l
ansiwrap==0.8.3
appnope==0.1.0
attrs==17.4.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.2
boto3==1.5.14
botocore==1.8.28
certifi==2017.11.5
chardet==3.0.4
click==6.7
codecov==2.0.13
configparser==3.5.0
coverage==4.4.2
decorator==4.2.1
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.2.0
html5lib==1.0.1
idna==2.6
ipykernel==4.7.0
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.1
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
mock==2.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2
numpy==1.14.0
pandas==0.22.0
pandocfilters==1.4.2
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.3.1
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
Pygments==2.2.0
pytest==3.3.2
pytest-cov==2.5.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
s3transfer==0.1.12
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
terminado==0.8.1
testpath==0.3.1
textwrap3==0.9.1
tornado==4.5.3
tqdm==4.19.5
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.0
(my2env)
```

**Comment by willingc** [comment]
OK I figured out what the issue was.

IPython depends on decorator. There were two releases in the past day for decorator 4.2.0 and a fix 4.2.1. Since IPython does not pin decorator, the release updates were reflected in the tests. [ref decorator changelog](https://github.com/micheles/decorator/blob/master/CHANGES.md#421-2018-01-14)

cc / @rgbkrk @takluyver @minrk FYI...Heads up if you see it manifest in other places.

**Comment by rgbkrk** [comment]
You both rock! Thank you @willingc and @MSeal!

**Comment by takluyver** [comment]
Thanks for the heads up @willingc - we did indeed get reports of this in ipython and in notebook.
